table fact_balance_mercado
	lineageTag: 70da29e5-3c00-4bbd-80dd-5c531c8330fb

	column Concepto
		dataType: string
		lineageTag: 2ea370b4-f247-46d9-8a61-f6f6df80076a
		summarizeBy: none
		sourceColumn: Concepto

		annotation SummarizationSetBy = Automatic

	column Anio
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ae979b0a-da13-4591-80cd-1bb9b45b7f8d
		summarizeBy: none
		sourceColumn: Anio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Miles_Toneladas
		dataType: int64
		formatString: 0
		lineageTag: 742144c0-70cf-437e-942e-dec05d207924
		summarizeBy: sum
		sourceColumn: Miles_Toneladas

		annotation SummarizationSetBy = Automatic

	partition fact_balance_mercado = m
		mode: import
		source =
				let
				    Origen = Pdf.Tables(File.Contents("C:\Users\Maximiliano\OneDrive\Escritorio\proyecto github\analisis-mercado-cobre-chile\data\raw\tendencias_precio_cobre_2026_2027.pdf"), [Implementation="1.3"]),
				    Table024 = Origen{[Id="Table024"]}[Data],
				    #"Tipo cambiado2" = Table.TransformColumnTypes(Table024,{{"Column1", type text}, {"Column2", Int64.Type}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}}),
				    #"Encabezados promovidos1" = Table.PromoteHeaders(#"Tipo cambiado2", [PromoteAllScalars=true]),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Encabezados promovidos1",{"% var", "% var_1"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas quitadas",{{"Column1", "Concepto"}, {"2026 f", "2026"}, {"2027 f", "2027"}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columnas con nombre cambiado",".","",Replacer.ReplaceText,{"2026", "2027"}),
				    #"Otras columnas con anulación de dinamización" = Table.UnpivotOtherColumns(#"Valor reemplazado", {"Concepto"}, "Atributo", "Valor"),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Otras columnas con anulación de dinamización",{{"Atributo", "Anio"}, {"Valor", "Miles_Toneladas"}}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas con nombre cambiado1",{{"Miles_Toneladas", Int64.Type}, {"Anio", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

