table fact_produccion_mundial
	lineageTag: 701dd7bf-4695-4a83-a5c6-1590a186a0ea

	column País
		dataType: string
		lineageTag: 0a1c46db-a731-4919-9dfe-e3ce6f6baa7f
		summarizeBy: none
		sourceColumn: País

		annotation SummarizationSetBy = Automatic

	column Anio
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7f9eed4c-932f-43bf-ac72-b68ad7f2b24b
		summarizeBy: none
		sourceColumn: Anio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Miles_Toneladas
		dataType: int64
		formatString: 0
		lineageTag: 6b4d0b26-7fe0-429a-8e6d-83afae03c2c5
		summarizeBy: sum
		sourceColumn: Miles_Toneladas

		annotation SummarizationSetBy = Automatic

	partition fact_produccion_mundial = m
		mode: import
		source =
				let
				    Origen = Pdf.Tables(File.Contents("C:\Users\Maximiliano\OneDrive\Escritorio\proyecto github\analisis-mercado-cobre-chile\data\raw\tendencias_precio_cobre_2026_2027.pdf"), [Implementation="1.3"]),
				    Page1 = Origen{[Id="Page030"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Page1, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Anexo 1: Proyección mercado del cobre 2026-2027", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", Int64.Type}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Column2", "Column3"}),
				    #"Filas superiores quitadas" = Table.Skip(#"Columnas quitadas",1),
				    #"Filas inferiores quitadas" = Table.RemoveLastN(#"Filas superiores quitadas",1),
				    #"Encabezados promovidos1" = Table.PromoteHeaders(#"Filas inferiores quitadas", [PromoteAllScalars=true]),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Encabezados promovidos1",{{"País", type text}, {"2025", Int64.Type}, {"2026f", Int64.Type}, {"var%", Percentage.Type}, {"2027f", Int64.Type}, {"var%_1", Percentage.Type}}),
				    #"Columnas quitadas1" = Table.RemoveColumns(#"Tipo cambiado1",{"var%", "var%_1"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas quitadas1",{{"2026f", "2026"}, {"2027f", "2027"}}),
				    #"Filas filtradas" = Table.SelectRows(#"Columnas con nombre cambiado", each ([País] <> "Mundo")),
				    #"Otras columnas con anulación de dinamización" = Table.UnpivotOtherColumns(#"Filas filtradas", {"País"}, "Atributo", "Valor"),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Otras columnas con anulación de dinamización",{{"Atributo", "Anio"}, {"Valor", "Miles_Toneladas"}}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Columnas con nombre cambiado1",{{"Anio", Int64.Type}})
				in
				    #"Tipo cambiado2"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

