table fact_produccion_condicion
	lineageTag: 153bf0fd-2b11-439d-bfe2-43664f66efcc

	column Condicion
		dataType: string
		lineageTag: 94e19827-4961-455f-8a33-9f65abbfb768
		summarizeBy: none
		sourceColumn: Condicion

		annotation SummarizationSetBy = Automatic

	column Anio
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ce327725-7769-4a88-9f85-644508ec4e5f
		summarizeBy: none
		sourceColumn: Anio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Toneladas
		dataType: int64
		formatString: 0
		lineageTag: 56bed8b5-eea8-44d8-86a6-18a8d4918d04
		summarizeBy: sum
		sourceColumn: Toneladas

		annotation SummarizationSetBy = Automatic

	partition fact_produccion_condicion = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\Maximiliano\OneDrive\Escritorio\proyecto github\analisis-mercado-cobre-chile\proyeccion_produccion_2025_2034 - page 26.xlsx"), null, true),
				    #"Table 4_Sheet" = Origen{[Item="Table 4",Kind="Sheet"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Table 4_Sheet",{{"Column1", type text}, {"Column2", Int64.Type}, {"Column3", Int64.Type}, {"Column4", Int64.Type}, {"Column5", Int64.Type}, {"Column6", Int64.Type}, {"Column7", Int64.Type}, {"Column8", Int64.Type}, {"Column9", Int64.Type}, {"Column10", Int64.Type}, {"Column11", Int64.Type}}),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Tipo cambiado", [PromoteAllScalars=true]),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Condición [tpa Cu Fino]", type text}, {"2025", Int64.Type}, {"2026", Int64.Type}, {"2027", Int64.Type}, {"2028", Int64.Type}, {"2029", Int64.Type}, {"2030", Int64.Type}, {"2031", Int64.Type}, {"2032", Int64.Type}, {"2033", Int64.Type}, {"2034", Int64.Type}}),
				    #"Otras columnas con anulación de dinamización" = Table.UnpivotOtherColumns(#"Tipo cambiado1", {"Condición [tpa Cu Fino]"}, "Atributo", "Valor"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Otras columnas con anulación de dinamización",{{"Atributo", "Anio"}, {"Valor", "Toneladas"}, {"Condición [tpa Cu Fino]", "Condicion"}}),
				    #"Filas filtradas" = Table.SelectRows(#"Columnas con nombre cambiado", each ([Condicion] <> "Total")),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Filas filtradas",{{"Anio", Int64.Type}})
				in
				    #"Tipo cambiado2"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

